<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\InternetTechLab1.Models\InternetTechLab1.Models.csproj" />
    <ProjectReference Include="..\InternetTechLab1.Helpers\InternetTechLab1.Helpers.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
