// <auto-generated />
using System;
using InternetTechLab1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternetTechLab1.Data.Migrations
{
    [DbContext(typeof(GitHubDbContext))]
    [Migration("20260404084310_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("GitHubUserEntityGitHubUserEntity", b =>
                {
                    b.Property<int>("FollowersListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GitHubUserEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FollowersListId", "GitHubUserEntityId");

                    b.HasIndex("GitHubUserEntityId");

                    b.ToTable("UserFollowers", (string)null);
                });

            modelBuilder.Entity("InternetTechLab1.Data.Models.GitHubRepoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ForksCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GitHubUserEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StargazersCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GitHubUserEntityId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Repos");
                });

            modelBuilder.Entity("InternetTechLab1.Data.Models.GitHubUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("Followers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Following")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicRepos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GitHubUserEntityGitHubUserEntity", b =>
                {
                    b.HasOne("InternetTechLab1.Data.Models.GitHubUserEntity", null)
                        .WithMany()
                        .HasForeignKey("FollowersListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternetTechLab1.Data.Models.GitHubUserEntity", null)
                        .WithMany()
                        .HasForeignKey("GitHubUserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InternetTechLab1.Data.Models.GitHubRepoEntity", b =>
                {
                    b.HasOne("InternetTechLab1.Data.Models.GitHubUserEntity", null)
                        .WithMany("Repositories")
                        .HasForeignKey("GitHubUserEntityId");

                    b.HasOne("InternetTechLab1.Data.Models.GitHubUserEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("InternetTechLab1.Data.Models.GitHubUserEntity", b =>
                {
                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
